// Generated by the Supabase MCP (`generate_typescript_types`). Do not edit by
// hand; regenerate after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      championships: {
        Row: {
          created_at: string
          criteria: Json
          event_date: string
          id: string
          location: string
          name: string
          owner_id: string
          public_slug: string
          status: Database["public"]["Enums"]["championship_status"]
        }
        Insert: {
          created_at?: string
          criteria: Json
          event_date: string
          id?: string
          location?: string
          name: string
          owner_id?: string
          public_slug?: string
          status?: Database["public"]["Enums"]["championship_status"]
        }
        Update: {
          created_at?: string
          criteria?: Json
          event_date?: string
          id?: string
          location?: string
          name?: string
          owner_id?: string
          public_slug?: string
          status?: Database["public"]["Enums"]["championship_status"]
        }
        Relationships: [
          {
            foreignKeyName: "championships_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      divisions: {
        Row: {
          advance_per_group: number | null
          bracket: Json | null
          championship_id: string
          created_at: string
          format: Database["public"]["Enums"]["bracket_format"]
          group_key: string | null
          group_size: number | null
          has_bracket: boolean | null
          id: string
          name: string
          status: Database["public"]["Enums"]["division_status"]
          third_place_match: boolean
        }
        Insert: {
          advance_per_group?: number | null
          bracket?: Json | null
          championship_id: string
          created_at?: string
          format?: Database["public"]["Enums"]["bracket_format"]
          group_key?: string | null
          group_size?: number | null
          has_bracket?: boolean | null
          id?: string
          name: string
          status?: Database["public"]["Enums"]["division_status"]
          third_place_match?: boolean
        }
        Update: {
          advance_per_group?: number | null
          bracket?: Json | null
          championship_id?: string
          created_at?: string
          format?: Database["public"]["Enums"]["bracket_format"]
          group_key?: string | null
          group_size?: number | null
          has_bracket?: boolean | null
          id?: string
          name?: string
          status?: Database["public"]["Enums"]["division_status"]
          third_place_match?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "divisions_championship_id_fkey"
            columns: ["championship_id"]
            isOneToOne: false
            referencedRelation: "championships"
            referencedColumns: ["id"]
          },
        ]
      }
      presets: {
        Row: {
          created_at: string
          criteria: Json
          id: string
          name: string
          owner_id: string | null
        }
        Insert: {
          created_at?: string
          criteria: Json
          id?: string
          name: string
          owner_id?: string | null
        }
        Update: {
          created_at?: string
          criteria?: Json
          id?: string
          name?: string
          owner_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "presets_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          full_name: string
          id: string
        }
        Insert: {
          created_at?: string
          full_name?: string
          id: string
        }
        Update: {
          created_at?: string
          full_name?: string
          id?: string
        }
        Relationships: []
      }
      registrations: {
        Row: {
          academy: string
          belt: string
          birth_date: string
          championship_id: string
          coach: string
          consent_at: string
          created_at: string
          division_id: string | null
          email: string
          full_name: string
          gender: Database["public"]["Enums"]["gender"]
          guardian_consent_at: string | null
          guardian_name: string | null
          guardian_phone: string | null
          id: string
          phone: string
          status: Database["public"]["Enums"]["registration_status"]
          weight_kg: number
        }
        Insert: {
          academy: string
          belt: string
          birth_date: string
          championship_id: string
          coach?: string
          consent_at: string
          created_at?: string
          division_id?: string | null
          email: string
          full_name: string
          gender: Database["public"]["Enums"]["gender"]
          guardian_consent_at?: string | null
          guardian_name?: string | null
          guardian_phone?: string | null
          id?: string
          phone: string
          status?: Database["public"]["Enums"]["registration_status"]
          weight_kg: number
        }
        Update: {
          academy?: string
          belt?: string
          birth_date?: string
          championship_id?: string
          coach?: string
          consent_at?: string
          created_at?: string
          division_id?: string | null
          email?: string
          full_name?: string
          gender?: Database["public"]["Enums"]["gender"]
          guardian_consent_at?: string | null
          guardian_name?: string | null
          guardian_phone?: string | null
          id?: string
          phone?: string
          status?: Database["public"]["Enums"]["registration_status"]
          weight_kg?: number
        }
        Relationships: [
          {
            foreignKeyName: "registrations_championship_id_fkey"
            columns: ["championship_id"]
            isOneToOne: false
            referencedRelation: "championships"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "registrations_division_id_fkey"
            columns: ["division_id"]
            isOneToOne: false
            referencedRelation: "divisions"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_public_championship: {
        Args: { slug: string }
        Returns: {
          adult_age: number
          belts: Json
          event_date: string
          location: string
          name: string
          status: Database["public"]["Enums"]["championship_status"]
        }[]
      }
      get_public_divisions: { Args: { slug: string }; Returns: Json }
      submit_registration: {
        Args: {
          academy: string
          belt: string
          birth_date: string
          coach: string
          consent: boolean
          email: string
          full_name: string
          gender: Database["public"]["Enums"]["gender"]
          guardian_consent?: boolean
          guardian_name?: string
          guardian_phone?: string
          phone: string
          slug: string
          weight_kg: number
        }
        Returns: string
      }
    }
    Enums: {
      bracket_format: "single_elimination" | "repechage" | "round_robin"
      championship_status:
        | "draft"
        | "registration_open"
        | "registration_closed"
        | "in_progress"
        | "finished"
      division_status: "draft" | "locked" | "in_progress" | "finished"
      gender: "male" | "female"
      registration_status: "pending" | "approved" | "rejected"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never
